name: oreally
version: 0.1.0.0
github: "arturictus/oreally"
license: BSD3
author: "Artur Panach"
maintainer: "artur.panach@gmail.com"
copyright: "2022 Artur Panach"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/arturictus/oreally#readme>

dependencies:
  - base >= 4.7 && < 5
  - network-uri >= 2.7.0
  - bytestring
  - text
  - command >= 0.1

library:
  source-dirs: src

executables:
  oreally-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - oreally

tests:
  oreally-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - oreally
      - hspec
      - hspec-discover
